### PR TITLE
Part 3

### PR DESCRIPTION
**Pull request by hayleychangs**
1. add: static page of attraction.html with RWD.
2. feat: get data from API(/api/attraction/{attractionId}) and display the result on attraction.html.
3. feat: radio buttons for choosing time of the guide tour and show the guide fee.
4. add: add a tag  on each attraction block in index.html, link to (/attraction/{attractionId}).
5. feat: attraction images slide show in attraction.html.

Please test the URLs below.
http://18.177.184.255:3000/
http://18.177.184.255:3000/attraction/10

詠婷

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Missing two separator lines.
2. Padding of date input.
3. Image slider should keep no margin space with navigator bar in mobile version.

**Comment by hayleychangs** [comment]
1. fix: two separator lines
2. fix: padding of date input
3. fix: Image slider keep no margin space with navigator bar in mobile version
4. add: image slide auto-play
5. add: Python Flask Blueprint

Please test the URLs below.
http://18.177.184.255:3000/
http://18.177.184.255:3000/attraction/10

詠婷

**Review by cwpeng — COMMENTED** [review]
Your live URLs are borken.

**Comment by hayleychangs** [comment]
fixed the instance status check failure on AWS.
sorry for your inconvenience!

Please test the URLs below.
http://18.177.184.255:3000/
http://18.177.184.255:3000/attraction/10

詠婷

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by hayleychangs** [comment]
Thanks for the review!

**Pull request merged**
